-- cricstat semantic catalog (P0, 2026-10-06): one description per view and column, written from
-- docs/F4-metric-dictionary.md. Loaded into semantic_catalog by every build. It feeds the API's meta.metrics
-- (F5 §2), GET /v1/meta/metrics, the Methodology page and the agent's schema prompt (F4 §4).
-- column_name '' describes the object itself. Keep the wording in step with F4 when a rule changes.

INSERT INTO semantic_catalog (object_name, column_name, description) VALUES
-- ── Views (the only place ratios are defined) ──
('v_player_batting', '', 'Career batting per player and scope (TEST, ODI, T20I, LEAGUES, ALL, a league slug or any other format key). Super overs excluded.'),
('v_player_batting', 'scope', 'TEST, ODI, T20I, LEAGUES (featured T20 leagues), ALL (official internationals + featured leagues), a competition slug such as ipl, or another format key.'),
('v_player_batting', 'matches', 'Matches on the team sheet (playing XI, supersub or replacement that came in). Matches abandoned without a ball bowled are not counted.'),
('v_player_batting', 'innings', 'Batting innings: the player faced a ball, was at the non-striker''s end when a ball was bowled, or was dismissed.'),
('v_player_batting', 'not_outs', 'Innings in which the player was not out. Retired hurt and retired not out count as not out; retired out is out.'),
('v_player_batting', 'runs', 'Runs scored off the bat, including off no-balls. Byes, leg-byes, wides and penalty runs are not the batter''s.'),
('v_player_batting', 'balls_faced', 'Every delivery received except wides; no-balls count as balls faced.'),
('v_player_batting', 'high_score', 'Highest runs in one innings; on equal runs the not-out innings is shown (see high_score_not_out).'),
('v_player_batting', 'high_score_not_out', '1 if the high score was not out (shown as 100*).'),
('v_player_batting', 'average', 'Batting average = runs ÷ dismissals (innings − not outs). Null when the player has never been out.'),
('v_player_batting', 'strike_rate', 'Batting strike rate = runs × 100 ÷ balls faced (wides excluded).'),
('v_player_batting', 'hundreds', 'Innings of 100 or more.'),
('v_player_batting', 'fifties', 'Innings of 50 to 99 (a hundred is not also a fifty).'),
('v_player_batting', 'ducks', 'Innings of 0 and out (0 not out is not a duck).'),
('v_player_batting', 'fours', 'Boundary fours: 4 runs off the bat that were not all run or overthrows.'),
('v_player_batting', 'sixes', 'Sixes off the bat.'),
('v_player_batting', 'first_date', 'Date of the first match in this scope.'),
('v_player_batting', 'last_date', 'Date of the latest match in this scope.'),
('v_player_bowling', '', 'Career bowling per player and scope. Super overs excluded.'),
('v_player_bowling', 'innings', 'Innings in which the player bowled at least one delivery.'),
('v_player_bowling', 'legal_balls', 'Deliveries that were neither a wide nor a no-ball.'),
('v_player_bowling', 'overs_display', 'Legal balls in 6-ball notation, e.g. 37.3 (also for the Hundred).'),
('v_player_bowling', 'maidens', 'Complete overs bowled entirely by this bowler conceding 0 runs (byes and leg-byes allowed). A shared over is no one''s maiden; there are no maidens in the Hundred.'),
('v_player_bowling', 'runs_conceded', 'Runs off the bat plus all wide and no-ball runs. Byes, leg-byes and penalty runs are not charged to the bowler.'),
('v_player_bowling', 'wickets', 'Dismissals credited to the bowler: bowled, caught, caught and bowled, lbw, stumped, hit wicket. Run outs, obstructing the field, handled the ball, hit the ball twice, timed out and retirements are not.'),
('v_player_bowling', 'average', 'Bowling average = runs conceded ÷ wickets. Null with no wickets.'),
('v_player_bowling', 'economy', 'Economy = runs conceded × 6 ÷ legal balls (per 6 legal balls in every format, including the Hundred). Byes, leg-byes and penalty runs are not charged to the bowler; super overs excluded.'),
('v_player_bowling', 'strike_rate', 'Bowling strike rate = legal balls ÷ wickets.'),
('v_player_bowling', 'best_bowling_wkts', 'Best bowling in an innings: most wickets, then fewest runs (5/41 beats 5/50 beats 4/10). Wickets part.'),
('v_player_bowling', 'best_bowling_runs', 'Runs part of the best bowling figures.'),
('v_player_bowling', 'four_wkt_hauls', 'Innings with exactly 4 wickets.'),
('v_player_bowling', 'five_wkt_hauls', 'Innings with 5 or more wickets.'),
('v_player_fielding', '', 'Career fielding per player and scope. Super overs excluded.'),
('v_player_fielding', 'catches', 'Catches as a fielder, plus caught-and-bowled for the bowler. Catches taken as a substitute are not career catches.'),
('v_player_fielding', 'stumpings', 'Stumpings credited to the listed fielder (the wicketkeeper).'),
('v_player_fielding', 'run_outs', 'Run-out involvements. Not an official statistic: counts each fielder listed in a run-out, so shared run-outs credit both.'),
('v_player_fielding', 'dismissals', 'Catches + stumpings (run-out involvements excluded).'),
('v_player_phase', '', 'Limited-overs phase splits per player and format. T20: overs 1–6, 7–15, 16–20; ODI: overs 1–10, 11–40, 41–50 (labelled by overs, not powerplay); the Hundred: balls 1–25, 26–75, 76–100. Super overs excluded.'),
('v_player_phase', 'phase', 'powerplay, middle or death (fixed over ranges, also in reduced-overs matches).'),
('v_player_phase', 'bat_strike_rate', 'Runs × 100 ÷ balls faced in this phase.'),
('v_player_phase', 'bowl_economy', 'Runs conceded × 6 ÷ legal balls in this phase.'),
('v_team_record', '', 'Team record per format. A team is a name + gender + team type (India men and India women are different teams).'),
('v_team_record', 'matches', 'Matches with at least one ball bowled. Matches abandoned without a ball are excluded.'),
('v_team_record', 'tied', 'Tied matches, including ties decided by a super over or bowl-out (the winner of those is stored separately).'),
('v_team_record', 'win_pct', 'Win % = won ÷ (matches − no results) × 100. Ties and draws stay in the denominator.'),
('v_head_to_head', '', 'Team against one opponent, per format.'),
('v_head_to_head', 'win_pct', 'Win % = won ÷ (matches − no results) × 100.'),
-- ── Tables the agent and API read ──
('players', '', 'People from the Cricsheet Register; player_id is the 8-hex Cricsheet identifier. Players have no country field; see player_teams.'),
('player_teams', '', 'Teams a player has represented, from team sheets of matches with play.'),
('player_names', '', 'Name variants for search: Register names, scorecard names and derived surnames.'),
('player_career', '', 'Counts per player and scope behind the v_player_* views. Ratios are never stored.'),
('player_year', '', 'Counts per player, scope and calendar year.'),
('batting_innings', '', 'One row per player per batting innings (the batting atom), including super overs flagged is_super_over.'),
('bowling_innings', '', 'One row per bowler per innings (the bowling atom), including super overs flagged is_super_over.'),
('bowling_innings', 'wides', 'Wide deliveries bowled, counted as balls. Their runs are extras in the team total and are also charged to the bowler''s runs_conceded; a wide is not a legal ball.'),
('bowling_innings', 'noballs', 'No-balls bowled, counted as balls. The no-ball runs are extras in the team total and are also charged to the bowler''s runs_conceded (with any runs off the bat); a no-ball is not a legal ball.'),
('fielding_events', '', 'Catches, stumpings, run-out involvements and substitute catches per player per innings (no super overs).'),
('phase_stats', '', 'Batting and bowling counts per player, innings and phase in limited-overs cricket (no super overs).'),
('team_results', '', 'One row per team per match with play: won, lost, tied, drawn or no_result, and home/away/neutral from the venue''s country.'),
('team_results', 'home_away', 'home when the venue''s country is the team, away when it is the opponent, else neutral. Null for league teams and venues not yet mapped.'),
('matches', '', 'One row per Cricsheet match. match_id is text (25 ids are not numeric). result is win, tie, draw or no_result; decided_by says how a tie was settled.'),
('matches', 'method', 'D/L, VJD, Awarded or Lost fewer wickets when the result needed one. D/L results count as normal wins.'),
('deliveries', '', 'Every ball bowled, legal or not (over_no is 0-based; seq is the order within the over).'),
('competitions', '', 'Cricsheet events. is_featured marks the leagues on the Leagues tab (IPL, BBL, PSL, CPL, SA20, MLC, T20 Blast, The Hundred, WPL, WBBL).'),
('venues', '', 'Grounds as Cricsheet names them; canonical_venue_key groups spelling variants; country comes from a hand-checked map.'),
('build_info', '', 'One row per serving-database build; data_as_of is the latest match date in the data.');
