"""Fetch national flags for cricstat's team badges (P0.4) — one-off, re-run when new teams appear.

    python3 cricstat/tools/fetch_flags.py

Source: Wikimedia Commons "Flag of …" SVGs. A flag is kept only when Commons reports its licence as
public domain or CC0 (a public-domain dedication); files are stored in cricstat/web/flags/ (served by our own Nginx — nothing loads from
third parties) and listed in cricstat/web/assets/flags.js with their source and licence.
Flags are shown at their own proportions (e.g. India 3:2, as its Flag Code requires), never
stretched or cropped. Not used: West Indies (a multi-nation team whose emblem is a board logo),
Ireland (Cricket Ireland represents the whole island) and composite sides (World XI etc.); those
keep the colour badge, as do club sides.
"""
import json
import os
import re
import time
import urllib.parse
import urllib.request

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
OUT = os.path.join(ROOT, "cricstat", "web", "flags")
JS = os.path.join(ROOT, "cricstat", "web", "assets", "flags.js")
API = os.environ.get("CRICSTAT_API", "http://127.0.0.1:8040")
UA = "pandyaHomeLab-cricstat/0.1 (https://pandyahomelab.com/cricket/; flags, one-off)"
# An SVG opened directly is a document on our origin: refuse anything active or external.
UNSAFE = re.compile(rb"<script|javascript:|\son[a-z]+\s*=|<foreignObject|<iframe|(?:xlink:)?href=[\"']https?:",
                    re.IGNORECASE)
SKIP = {"West Indies", "Ireland", "ICC World XI", "Asia XI", "Africa XI"}
TITLE = {  # Cricsheet team name → Commons file (when not "Flag of <name>.svg")
    "United States of America": "Flag of the United States.svg",
    "United Arab Emirates": "Flag of the United Arab Emirates.svg",
    "Netherlands": "Flag of the Netherlands.svg", "Czech Republic": "Flag of the Czech Republic.svg",
    "Bahamas": "Flag of the Bahamas.svg", "Philippines": "Flag of the Philippines.svg",
    "Gambia": "Flag of The Gambia.svg", "Cook Islands": "Flag of the Cook Islands.svg",
    "Cayman Islands": "Flag of the Cayman Islands.svg", "Isle of Man": "Flag of the Isle of Man.svg",
    "Maldives": "Flag of Maldives.svg", "Ivory Coast": "Flag of Côte d'Ivoire.svg",
    "Swaziland": "Flag of Eswatini.svg", "Turks and Caicos Island": "Flag of the Turks and Caicos Islands.svg",
    "Timor-Leste": "Flag of East Timor.svg", "St Helena": "Flag of Saint Helena.svg",
}


def get(url, binary=False):
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=30) as r:
        body = r.read()
    return body if binary else json.loads(body.decode("utf-8"))


def slug(name):
    return "".join(c if c.isalnum() else "-" for c in name.lower()).strip("-")


def main():
    teams = get(API + "/v1/teams?type=international")["data"]
    names = sorted({t["name"] for t in teams if t["matches"] >= 20} - SKIP)
    os.makedirs(OUT, exist_ok=True)
    flags, skipped = {}, []
    for name in names:
        title = "File:" + TITLE.get(name, "Flag of %s.svg" % name)
        q = urllib.parse.urlencode({"action": "query", "titles": title, "prop": "imageinfo",
                                    "iiprop": "url|extmetadata|size", "format": "json",
                                    "formatversion": 2})
        page = get("https://commons.wikimedia.org/w/api.php?" + q)["query"]["pages"][0]
        info = (page.get("imageinfo") or [None])[0]
        if not info:
            skipped.append("%s (no file %s)" % (name, title))
            continue
        lic = (info.get("extmetadata", {}).get("LicenseShortName", {}) or {}).get("value", "")
        if "public domain" not in lic.lower() and lic.strip().upper() != "CC0":
            skipped.append("%s (licence: %s)" % (name, lic or "unknown"))
            continue
        svg = get(info["url"], binary=True)
        if UNSAFE.search(svg):
            skipped.append("%s (SVG has scripts or external references)" % name)
            continue
        fname = slug(name) + ".svg"
        with open(os.path.join(OUT, fname), "wb") as f:
            f.write(svg)
        flags[name] = {"file": fname, "w": info["width"], "h": info["height"],
                       "source": info["descriptionurl"], "licence": lic}
        time.sleep(0.5)
    with open(JS, "w", encoding="utf-8") as f:
        f.write("/* Generated by cricstat/tools/fetch_flags.py — national flags from Wikimedia Commons,\n"
                "   public domain, self-hosted in /cricket/flags/. Do not edit by hand. */\n")
        f.write("window.CRICSTAT_FLAGS = %s;\n" % json.dumps(flags, indent=1, ensure_ascii=False))
    print("kept %d flags; skipped %d: %s" % (len(flags), len(skipped), "; ".join(skipped)))


if __name__ == "__main__":
    main()
